
  <div class="container">
      <div class="row m-4">
          <center><h1>INSERTAR DATOS</h1></center>
      </div>
      <div class="row">
          <div class="col-1 col-md-3"></div>
          <div class="col-10 col-md-6 border shadow p-4">
              <form action="?controller=insertar" method="post">
                  <div class="input-group mb-3">
                      <input type="text" class="form-control" placeholder="nombre" name="nombre">
                  </div>
                  <div class="input-group mb-3">
                      <input type="text" class="form-control" placeholder="apellido" name="apellido">
                  </div>

                  <div class="input-group mb-3">
                      <input type="text" class="form-control" placeholder="telefono" name="telefono">
                  </div>
                  <input type="submit" class="btn btn-success" value="Guardar Datos">
              </form>
          </div>
          <div class="col-1 col-md-3"></div>
      </div>
  </div>